#!/usr/bin/env bash

if [ $# -ne 1 ]; then
    echo "Usage: $0 [<arch> ...]"
    exit 1
fi

COMMON=common
SUFFIX=.entry.s

if [ ! -d $COMMON ]; then
	echo "$COMMON/ directory not found"
	exit 1
fi

for ARCH in $*; do

	if [ ! -d $ARCH ]; then
		echo "$ARCH/ directory not found"
		exit 1
	fi

	pushd $COMMON
	FILES=$(fd --glob "*$SUFFIX" . | sort)
	popd

	for FILE in $FILES; do
		PARENT=$(dirname $FILE)
		PARENT=${PARENT:2}
		NAME=$(basename $FILE $SUFFIX)
		TARGET="$ARCH/$PARENT/$NAME.s"
		mkdir -p $(dirname $TARGET)
		echo "Generating $TARGET"
		echo "; DO NOT EDIT THIS FILE" > $TARGET
		echo "; GENERATED AUTOMATICALLY BY $0" >> $TARGET
		echo "" >> $TARGET
		echo "%include \"elf/$ARCH/callconv.inc.s\"" >> $TARGET
		echo "%include \"elf/$COMMON/$PARENT/$(basename $FILE)\"" >> $TARGET
		echo "" >> $TARGET
	done
	echo "Done"
done
